<?php

/**
 * @file
 * Webform captcha mandatory module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\webform\Utility\WebformFormHelper;

/**
 * Implements hook_webform_submission_form_alter().
 */
function webform_captcha_mandatory_webform_submission_form_alter(&$form, FormStateInterface $form_state, $form_id) {

    $elements = WebformFormHelper::flattenElements($form);

    if(!has_captcha_webform($elements)) {
        $form['#validate'][] = 'webform_captcha_mandatory_validate';
    }

}

function webform_captcha_mandatory_validate(&$form, FormStateInterface $form_state) {
    $form_state->setErrorByName('webform_captcha_mandatory_alter', 
      t('Erro: Submissão não enviada. Este Formulário está inválido e inseguro. <br>
      Entre em contato com o(a) responsável pelo site para inserção do (re)captcha'));
}

/**
 * To know if there is captcha defined for a Webform.
 * @param Array
 *
 * @return Boolean
 * TRUE if there is elements, FALSE otherwise.
 */
function has_captcha_webform(Array $elements) {

    foreach($elements as $element) {
       if($element['#type'] == 'captcha') {
           return TRUE;
       }
    }

    return FALSE;

}
