<?php

/**
 * @file
 * Webform captcha mandatory module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\webform\Utility\WebformFormHelper;

/**
 * Implements hook_webform_submission_form_alter().
 */
function webform_captcha_mandatory_webform_submission_form_alter(&$form, FormStateInterface $form_state, $form_id) {

    $elements = WebformFormHelper::flattenElements($form);

    $has_captcha = false;
    foreach($elements['elements'] as $element){
       if($element['#type'] == 'captcha') $has_captcha = true;
    }

    if (!$has_captcha) {
      $form['#validate'][] = 'webform_captcha_mandatory_validate';
    }
}

function webform_captcha_mandatory_validate(&$form, FormStateInterface $form_state) {
    $form_state->setErrorByName('webform_captcha_mandatory_alter', 
      t('Erro: Submissão não enviada. Este Formulário está inválido e inseguro. <br>
      Entre em contato com o(a) responsável pelo site para inserção do (re)captcha'));
}
